### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by zmf2022** [SimonTheVillain/ScalableFusion#10]
I have building success, but do not konw how to run it.  it miss much configuration file

**Comment by SimonTheVillain** [comment]
Honestly, I stopped developing this code long ago but I might be able to help. How are you trying to run the reconstruction? Do you have a TUM style dataset? Did you create the associations.txt?

EDIT: What are you expecting from this reconstruction? Depending on what you want to achieve, I might be able to tell you if and how this is achievable with ScalableFusion.
Also sorry for the code-quality in this repo, I was quite inexperienced when starting this project.

**Comment by zmf2022** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，已收到您的邮件，将尽快给您回复！

**Comment by zmf2022** [comment]
Thank you very much, i have downlaod tum datasets
&nbsp;and generating associate.txt, but it seems need something other files,such as rgb_exposure.txt extrinsics.yml?





---Original---
From: ***@***.***&gt;
Date: Wed, Jan 18, 2023 04:39 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SimonTheVillain/ScalableFusion] How to run? (Issue #10)




 
Honestly, I stopped developing this code long ago but I might be able to help. How are you trying to run the reconstruction? Do you have a TUM style dataset? Did you create the associations.txt?

**Comment by SimonTheVillain** [comment]
Thats unfortunate, I hoped that I would have implemented proper fallbacks in case no configs are provided.
Try this file as intrinsics file and put it in the folder above your your sequence
[extrinsics.zip](https://github.com/SimonTheVillain/ScalableFusion/files/10443363/extrinsics.zip)
The rgb_exposure.txt looks something like this: 
`30 rgb/000000.004281.png
30 rgb/000000.028649.png
...`
Its probably best to write a small python script to generate this sequence for you. The first number is the exposure time used during capture. It probably was not constant during TUMs capture process, but it was not logged either. It thus is best to just set it constant.
In case you just want to check out any sequence, download [this](https://drive.google.com/file/d/1EbsEnF4fpi-QDAYCg9yh03Y54eZ9W1zF/view?usp=sharing). If even that sequence doesn't work, I have made a few changes locally that I might need to push to master for you to run this. 

It would still be nice if you could tell me what you are expecting from this reconstruction. I have a good grasp on what it does and what it doesn't do. I hope it is not your professor, boss or somebody else forcing you to get this code to work.
